jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: current date
      run: date
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - continue-on-error: true
      name: Commit files
      run: 'git config --local user.email "niumoo@126.com"

        git config --local user.name "niumoo"

        git pull

        git add README.md

        git add bing-wallpaper.md

        git add picture/*

        git add docs/*

        git add zh-cn/*

        git commit -m "update readme.md"

        '
    - continue-on-error: true
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.MY_GIT_TOKEN }}
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
